language: java
jdk:
- openjdk8

addons:
  sonarcloud:
    organization: "Albert Ku≈Çakowski"
    token:
      secure: 9albert6 # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=lab_0